# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2013
  project: Hide opcode cache check in system environment check
  version: 1.0
  release: 1.0.0
  latex_documents:
  - - Index
    - Hideopcodecachecheckinsystemenvironmentcheck.tex
    - Hide opcode cache check in system environment check
    - Adrian Dymorz
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
